# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - odoo-community-at

on:
  push:
    branches:
      - 18.0
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_65355b889a644215845c71154ccd929d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7ef332a864a94720acab5eb3ae67b1f1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_65355b889a644215845c71154ccd929d }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'odoo-community-at'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0d4fc335307a48ffa833553c589d1cd7 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_65355b889a644215845c71154ccd929d }}/appsvc/staticsite:${{ github.sha }}'